# Generated by Django 4.2 on 2024-09-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
